"use client";

import { useEffect, useState } from "react";
import api from "@/lib/api";
import type { AutoGapAnalysis, CV, CvData, MultiGapAnalysis } from "@/lib/types";
import { CVVersionManager } from "@/components/cv/CVVersionManager";
import { CVUploader } from "@/components/cv/CVUploader";
import { DescribeCvTab } from "@/components/cv/DescribeCvTab";
import { TemplateGenCvTab } from "@/components/cv/TemplateGenCvTab";
import { UploadImproveCvTab } from "@/components/cv/UploadImproveCvTab";
import { CvHtmlPreview } from "@/components/cv/CvHtmlPreview";
import { CvContentEditor } from "@/components/cv/CvContentEditor";
import { TemplateField } from "@/components/cv/TemplatePicker";
import { GapAnalysisCard } from "@/components/roadmap/GapAnalysisCard";
import { Modal } from "@/components/ui/Modal";
import { Toast } from "@/components/ui/Toast";
import {
  Sparkles,
  Target,
  Download,
  FileText,
  Trash2,
  Check,
  X,
  Eye,
  Pencil,
  ChevronDown,
  ChevronUp,
  Globe,
} from "lucide-react";

function generationModelLabel(cv: CV): string | null {
  const model = cv.structured_data?.["generation_model"];
  if (typeof model !== "string") return null;
  if (model.startsWith("gemini")) return "Generated by Gemini 2.0 Flash";
  if (model.includes("fallback")) return "Generated by Claude (fallback)";
  if (model.startsWith("claude")) return "Generated by Claude";
  return `Generated by ${model}`;
}

type CreateMode = "describe" | "template" | "improve" | "upload";

const CREATE_MODES: { id: CreateMode; label: string }[] = [
  { id: "describe", label: "Describe" },
  { id: "template", label: "Fill Template" },
  { id: "improve", label: "Upload & Improve" },
  { id: "upload", label: "Upload only" },
];

type ModalState =
  | { type: "tailor"; cv: CV }
  | { type: "gap"; cv: CV }
  | { type: "auto-gap"; cv: CV }
  | { type: "preview"; cv: CV }
  | { type: "edit"; cv: CV }
  | null;

export default function CVPage() {
  const [cvs, setCvs] = useState<CV[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activatingId, setActivatingId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [translatePopoverId, setTranslatePopoverId] = useState<string | null>(null);
  const [translatingId, setTranslatingId] = useState<string | null>(null);

  const [modal, setModal] = useState<ModalState>(null);
  const [jobDescription, setJobDescription] = useState("");
  const [working, setWorking] = useState(false);
  const [modalError, setModalError] = useState<string | null>(null);
  const [tailoredText, setTailoredText] = useState<string | null>(null);
  const [gapResult, setGapResult] = useState<MultiGapAnalysis | null>(null);
  const [autoGapResult, setAutoGapResult] = useState<AutoGapAnalysis | null>(null);
  const [autoGapWorking, setAutoGapWorking] = useState(false);
  const [openWeakSection, setOpenWeakSection] = useState<number | null>(null);
  const [editData, setEditData] = useState<CvData | null>(null);
  const [editTemplateId, setEditTemplateId] = useState("classic_blue_photo");
  const [parsingId, setParsingId] = useState<string | null>(null);

  const [createMode, setCreateMode] = useState<CreateMode>("describe");
  const [generatedCv, setGeneratedCv] = useState<CV | null>(null);

  async function loadCvs() {
    setLoading(true);
    setError(null);
    try {
      const { data } = await api.get<CV[]>("/cv/");
      setCvs(data);
    } catch {
      setError("Failed to load CVs.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadCvs();
  }, []);

  async function handleActivate(cv: CV) {
    setActivatingId(cv.id);
    try {
      await api.patch<CV>(`/cv/${cv.id}/activate`);
      await loadCvs();
    } catch {
      setError("Failed to set active CV.");
    } finally {
      setActivatingId(null);
    }
  }

  async function handleDelete(cv: CV) {
    setDeletingId(cv.id);
    try {
      await api.delete(`/cv/${cv.id}`);
      await loadCvs();
      setToast("CV deleted");
    } catch {
      setError("Failed to delete CV.");
    } finally {
      setDeletingId(null);
      setConfirmDeleteId(null);
    }
  }

  function openModal(type: "tailor" | "gap" | "preview", cv: CV) {
    setModal({ type, cv });
    setJobDescription("");
    setModalError(null);
    setTailoredText(null);
    setGapResult(null);
  }

  async function handleAutoGap(cv: CV) {
    setModal({ type: "auto-gap", cv });
    setModalError(null);
    setAutoGapResult(null);
    setOpenWeakSection(null);
    setAutoGapWorking(true);
    try {
      const { data } = await api.post<AutoGapAnalysis>(`/cv/${cv.id}/auto-gap-analysis`);
      setAutoGapResult(data);
    } catch {
      setModalError("Failed to run auto-analysis.");
    } finally {
      setAutoGapWorking(false);
    }
  }

  function openEditModal(cv: CV) {
    setModal({ type: "edit", cv });
    setEditData((cv.structured_data as CvData | null) ?? {});
    setEditTemplateId(cv.cv_template_id ?? "classic_blue_photo");
    setModalError(null);
  }

  async function handleEditClick(cv: CV) {
    if (cv.structured_data) {
      openEditModal(cv);
      return;
    }
    setParsingId(cv.id);
    try {
      const { data } = await api.post<CV>(`/cv/${cv.id}/parse`);
      setCvs((prev) => prev.map((c) => (c.id === data.id ? data : c)));
      openEditModal(data);
    } catch {
      setError("Failed to parse CV for editing.");
    } finally {
      setParsingId(null);
    }
  }

  function closeModal() {
    setModal(null);
    setEditData(null);
  }

  async function handleSubmitModal() {
    if (!modal || !jobDescription.trim()) return;
    if (modal.type !== "tailor" && modal.type !== "gap") return;
    setWorking(true);
    setModalError(null);
    try {
      if (modal.type === "tailor") {
        const { data } = await api.post<{ tailored_text: string }>(
          `/cv/${modal.cv.id}/tailor`,
          { job_description: jobDescription }
        );
        setTailoredText(data.tailored_text);
      } else {
        const { data } = await api.post<MultiGapAnalysis>(`/cv/${modal.cv.id}/gap-analysis`, {
          job_description: jobDescription,
        });
        setGapResult(data);
      }
    } catch {
      setModalError(
        modal.type === "tailor" ? "Failed to tailor CV." : "Failed to run gap analysis."
      );
    } finally {
      setWorking(false);
    }
  }

  async function handleSaveEdit() {
    if (!modal || modal.type !== "edit" || !editData) return;
    setWorking(true);
    setModalError(null);
    try {
      const { data } = await api.patch<CV>(`/cv/${modal.cv.id}/content`, {
        structured_data: editData,
        cv_template_id: editTemplateId,
      });
      setCvs((prev) => prev.map((c) => (c.id === data.id ? data : c)));
      if (generatedCv?.id === data.id) setGeneratedCv(data);
      setToast("CV updated");
      closeModal();
    } catch {
      setModalError("Failed to save changes.");
    } finally {
      setWorking(false);
    }
  }

  async function handleTranslate(cv: CV, targetLanguage: "Hebrew" | "English") {
    setTranslatingId(cv.id);
    setTranslatePopoverId(null);
    try {
      await api.post<CV>(`/cv/${cv.id}/translate?target_language=${encodeURIComponent(targetLanguage)}`);
      await loadCvs();
      setToast("Translation saved as new CV");
    } catch {
      setError("Failed to translate CV.");
    } finally {
      setTranslatingId(null);
    }
  }

  function handleGenerated(cv: CV) {
    setGeneratedCv(cv);
    setToast("CV generated");
    loadCvs();
  }

  function downloadTailored() {
    if (!tailoredText || !modal) return;
    const blob = new Blob([tailoredText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(modal.cv.version_name ?? "cv").replace(/\.[^.]+$/, "")}-tailored.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">My CVs</h1>
        <p className="mt-2 text-sm text-slate-400">
          Generate a polished, AI-written CV with a live preview, then edit, download, or tailor it.
        </p>
      </div>

      <div className="space-y-4">
        <div className="inline-flex flex-wrap gap-1 rounded-xl border border-white/10 bg-white/5 p-1">
          {CREATE_MODES.map((mode) => (
            <button
              key={mode.id}
              type="button"
              onClick={() => setCreateMode(mode.id)}
              className={`rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${
                createMode === mode.id
                  ? "bg-blue-500/20 text-blue-300"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              {mode.label}
            </button>
          ))}
        </div>

        <div className="glass-card p-5">
          {createMode === "describe" && <DescribeCvTab onGenerated={handleGenerated} />}
          {createMode === "template" && <TemplateGenCvTab onGenerated={handleGenerated} />}
          {createMode === "improve" && <UploadImproveCvTab onGenerated={handleGenerated} />}
          {createMode === "upload" && (
            <div className="space-y-3">
              <p className="text-sm text-slate-400">
                Upload your existing CV as-is. We won&apos;t change it.
              </p>
              <CVUploader
                onUploaded={() => {
                  loadCvs();
                  setToast("CV uploaded");
                }}
              />
            </div>
          )}
        </div>

        {generatedCv?.html_content && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-white">Preview</h2>
              <button
                type="button"
                onClick={() => openEditModal(generatedCv)}
                className="btn-secondary !px-3 !py-1.5 text-xs"
              >
                <Pencil className="h-3.5 w-3.5" />
                Edit content
              </button>
            </div>
            {generationModelLabel(generatedCv) && (
              <span className="inline-block rounded-full bg-blue-500/10 px-2.5 py-1 text-xs text-blue-300">
                {generationModelLabel(generatedCv)}
              </span>
            )}
            <CvHtmlPreview
              html={generatedCv.html_content}
              filename={generatedCv.version_name ?? "cv"}
            />
            <button
              type="button"
              onClick={() => handleAutoGap(generatedCv)}
              className="btn-secondary !px-3 !py-1.5 text-xs"
            >
              <Sparkles className="h-3.5 w-3.5" />
              Check my CV
            </button>
          </div>
        )}
      </div>

      {error && <p className="text-sm text-red-400">{error}</p>}

      <div className="space-y-4">
        <h2 className="text-lg font-semibold text-white">My Saved CVs</h2>
        {loading ? (
          <p className="text-sm text-slate-400">Loading…</p>
        ) : (
          <CVVersionManager
            cvs={cvs}
            onActivate={handleActivate}
            activatingId={activatingId}
            renderActions={(cv) => (
              <>
                {cv.html_content && (
                  <>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        openModal("preview", cv);
                      }}
                      className="btn-secondary !px-3 !py-1.5 text-xs"
                    >
                      <Eye className="h-3.5 w-3.5" />
                      Preview
                    </button>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        openEditModal(cv);
                      }}
                      className="btn-secondary !px-3 !py-1.5 text-xs"
                    >
                      <Pencil className="h-3.5 w-3.5" />
                      Edit
                    </button>
                  </>
                )}
                {!cv.html_content && (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleEditClick(cv);
                    }}
                    disabled={parsingId === cv.id}
                    className="btn-secondary !px-3 !py-1.5 text-xs"
                  >
                    <Pencil className="h-3.5 w-3.5" />
                    {parsingId === cv.id ? "Preparing…" : "Edit"}
                  </button>
                )}
                {cv.pdf_url && (
                  <a
                    href={cv.pdf_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    className="btn-secondary !px-3 !py-1.5 text-xs"
                  >
                    <FileText className="h-3.5 w-3.5" />
                    Download PDF
                  </a>
                )}
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    openModal("tailor", cv);
                  }}
                  className="btn-secondary !px-3 !py-1.5 text-xs"
                >
                  <Sparkles className="h-3.5 w-3.5" />
                  Tailor to Job
                </button>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    openModal("gap", cv);
                  }}
                  className="btn-secondary !px-3 !py-1.5 text-xs"
                >
                  <Target className="h-3.5 w-3.5" />
                  Gap Analysis
                </button>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleAutoGap(cv);
                  }}
                  className="btn-secondary !px-3 !py-1.5 text-xs"
                >
                  <Sparkles className="h-3.5 w-3.5" />
                  Auto-Analyse
                </button>
                <div className="relative">
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      setTranslatePopoverId(translatePopoverId === cv.id ? null : cv.id);
                    }}
                    disabled={translatingId === cv.id}
                    className="btn-secondary !px-3 !py-1.5 text-xs"
                  >
                    <Globe className="h-3.5 w-3.5" />
                    {translatingId === cv.id ? "Translating…" : "Translate"}
                  </button>
                  {translatePopoverId === cv.id && (
                    <div
                      onClick={(e) => e.stopPropagation()}
                      className="absolute left-0 top-full z-10 mt-1 w-48 rounded-xl border border-white/10 bg-slate-900 p-1 shadow-lg"
                    >
                      <button
                        type="button"
                        onClick={() => handleTranslate(cv, "Hebrew")}
                        className="block w-full rounded-lg px-3 py-1.5 text-left text-xs text-slate-200 hover:bg-white/10"
                      >
                        → Translate to Hebrew
                      </button>
                      <button
                        type="button"
                        onClick={() => handleTranslate(cv, "English")}
                        className="block w-full rounded-lg px-3 py-1.5 text-left text-xs text-slate-200 hover:bg-white/10"
                      >
                        → Translate to English
                      </button>
                    </div>
                  )}
                </div>
                {confirmDeleteId === cv.id ? (
                  <div className="flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 px-2 py-1 text-xs text-red-300">
                    <span>Delete this CV?</span>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDelete(cv);
                      }}
                      disabled={deletingId === cv.id}
                      className="flex items-center gap-1 rounded-lg bg-red-500/20 px-2 py-1 font-medium text-red-200 hover:bg-red-500/30"
                    >
                      <Check className="h-3 w-3" />
                      {deletingId === cv.id ? "Deleting…" : "Yes"}
                    </button>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setConfirmDeleteId(null);
                      }}
                      className="flex items-center gap-1 rounded-lg bg-white/5 px-2 py-1 font-medium text-slate-300 hover:bg-white/10"
                    >
                      <X className="h-3 w-3" />
                      Cancel
                    </button>
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      setConfirmDeleteId(cv.id);
                    }}
                    className="btn-secondary !px-3 !py-1.5 text-xs !text-red-400 hover:!bg-red-500/10"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                    Delete
                  </button>
                )}
              </>
            )}
          />
        )}
      </div>

      {modal && (modal.type === "tailor" || modal.type === "gap") && (
        <Modal
          title={
            modal.type === "tailor"
              ? `Tailor "${modal.cv.version_name ?? "CV"}" to a job`
              : `Gap analysis for "${modal.cv.version_name ?? "CV"}"`
          }
          onClose={closeModal}
        >
          <div className="space-y-4">
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-300">
                Job description
              </label>
              <textarea
                value={jobDescription}
                onChange={(e) => setJobDescription(e.target.value)}
                rows={6}
                placeholder="Paste the job description here…"
                className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-100 outline-none transition-colors placeholder:text-slate-500 focus:border-blue-500/50 focus:ring-2 focus:ring-blue-500/30"
              />
            </div>

            {modalError && <p className="text-sm text-red-400">{modalError}</p>}

            <button
              type="button"
              onClick={handleSubmitModal}
              disabled={working || !jobDescription.trim()}
              className="btn-primary"
            >
              {working
                ? "Working…"
                : modal.type === "tailor"
                  ? "Generate tailored CV"
                  : "Run gap analysis"}
            </button>

            {tailoredText && (
              <div className="space-y-3">
                <div className="max-h-80 overflow-y-auto whitespace-pre-wrap rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-slate-200">
                  {tailoredText}
                </div>
                <button type="button" onClick={downloadTailored} className="btn-secondary">
                  <Download className="h-3.5 w-3.5" />
                  Download as .txt
                </button>
              </div>
            )}

            {gapResult && (
              <div className="grid gap-4 md:grid-cols-2">
                <GapAnalysisCard analysis={gapResult.claude} label="Claude's opinion" />
                {gapResult.openai && (
                  <GapAnalysisCard analysis={gapResult.openai} label="GPT's opinion" />
                )}
              </div>
            )}
          </div>
        </Modal>
      )}

      {modal && modal.type === "auto-gap" && (
        <Modal title={`Auto-Analysis – ${modal.cv.version_name ?? "CV"}`} onClose={closeModal} wide>
          {autoGapWorking && <p className="text-sm text-slate-400">Analysing your CV…</p>}
          {modalError && <p className="text-sm text-red-400">{modalError}</p>}
          {autoGapResult && (
            <div className="space-y-6">
              <div className="flex flex-col items-center gap-3 sm:flex-row sm:items-start">
                <div
                  className="flex h-24 w-24 flex-shrink-0 items-center justify-center rounded-full"
                  style={{
                    background: `conic-gradient(${
                      autoGapResult.overall_score >= 70
                        ? "#10b981"
                        : autoGapResult.overall_score >= 40
                          ? "#f59e0b"
                          : "#dc2626"
                    } ${autoGapResult.overall_score * 3.6}deg, rgba(255,255,255,0.1) 0deg)`,
                  }}
                >
                  <div className="flex h-[4.5rem] w-[4.5rem] items-center justify-center rounded-full bg-slate-900">
                    <span className="text-xl font-bold text-white">
                      {autoGapResult.overall_score}
                    </span>
                  </div>
                </div>
                <div className="space-y-2">
                  <p className="text-sm text-slate-300">{autoGapResult.summary}</p>
                  {autoGapResult.missing_sections.length > 0 && (
                    <div className="flex flex-wrap gap-1.5">
                      {autoGapResult.missing_sections.map((s) => (
                        <span
                          key={s}
                          className="rounded-full bg-red-500/10 px-2 py-0.5 text-xs text-red-300"
                        >
                          Missing: {s}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {autoGapResult.recommended_roles.length > 0 && (
                <div className="space-y-2">
                  <h3 className="text-sm font-semibold text-white">Recommended Roles</h3>
                  <div className="grid gap-3 sm:grid-cols-2">
                    {autoGapResult.recommended_roles.map((role, i) => (
                      <div key={i} className="rounded-xl border border-white/10 bg-white/5 p-3">
                        <p className="text-sm font-semibold text-white">{role.role}</p>
                        <p className="mt-1 text-xs text-slate-400">{role.match_reason}</p>
                        <p className="mt-1 text-xs text-amber-300">Gap: {role.gap_to_close}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {autoGapResult.weak_sections.length > 0 && (
                <div className="space-y-2">
                  <h3 className="text-sm font-semibold text-white">Weak Sections</h3>
                  <div className="space-y-2">
                    {autoGapResult.weak_sections.map((section, i) => (
                      <div key={i} className="rounded-xl border border-white/10 bg-white/5">
                        <button
                          type="button"
                          onClick={() => setOpenWeakSection(openWeakSection === i ? null : i)}
                          className="flex w-full items-center justify-between px-3 py-2 text-left text-sm font-medium text-white"
                        >
                          {section.section}
                          {openWeakSection === i ? (
                            <ChevronUp className="h-4 w-4" />
                          ) : (
                            <ChevronDown className="h-4 w-4" />
                          )}
                        </button>
                        {openWeakSection === i && (
                          <div className="space-y-1 border-t border-white/10 px-3 py-2">
                            <p className="text-xs text-slate-400">{section.issue}</p>
                            <p className="text-xs text-emerald-300">{section.suggestion}</p>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {autoGapResult.quick_wins.length > 0 && (
                <div className="space-y-2">
                  <h3 className="text-sm font-semibold text-white">Quick Wins</h3>
                  <ul className="space-y-1.5">
                    {autoGapResult.quick_wins.map((win, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
                        <Check className="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-emerald-400" />
                        {win}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {autoGapResult.keywords_to_add.length > 0 && (
                <div className="space-y-2">
                  <h3 className="text-sm font-semibold text-white">Keywords to Add</h3>
                  <div className="flex flex-wrap gap-1.5">
                    {autoGapResult.keywords_to_add.map((kw) => (
                      <span
                        key={kw}
                        className="rounded-full bg-blue-500/10 px-2.5 py-1 text-xs text-blue-300"
                      >
                        {kw}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </Modal>
      )}

      {modal && modal.type === "preview" && modal.cv.html_content && (
        <Modal title={`Preview – ${modal.cv.version_name ?? "CV"}`} onClose={closeModal} wide>
          <div className="space-y-3">
            <CvHtmlPreview html={modal.cv.html_content} filename={modal.cv.version_name ?? "cv"} />
            <button
              type="button"
              onClick={() => handleAutoGap(modal.cv)}
              className="btn-secondary !px-3 !py-1.5 text-xs"
            >
              <Sparkles className="h-3.5 w-3.5" />
              Check my CV
            </button>
          </div>
        </Modal>
      )}

      {modal && modal.type === "edit" && editData && (
        <Modal title={`Edit – ${modal.cv.version_name ?? "CV"}`} onClose={closeModal} wide>
          <div className="space-y-4">
            <TemplateField
              selectedId={editTemplateId}
              onSelect={setEditTemplateId}
              accentColor={editData.accent_color ?? null}
              fontFamily={editData.font_family ?? null}
              onAccentChange={(color) =>
                setEditData((prev) => (prev ? { ...prev, accent_color: color ?? undefined } : prev))
              }
              onFontChange={(font) =>
                setEditData((prev) => (prev ? { ...prev, font_family: font ?? undefined } : prev))
              }
            />
            <CvContentEditor data={editData} onChange={setEditData} cvId={modal.cv.id} />
            {modalError && <p className="text-sm text-red-400">{modalError}</p>}
            <button type="button" onClick={handleSaveEdit} disabled={working} className="btn-primary">
              {working ? "Saving…" : "Save changes"}
            </button>
          </div>
        </Modal>
      )}

      {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
    </div>
  );
}
